# Generated by Django 2.2.2 on 2019-07-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0002_auto_20190707_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='cat',
            new_name='nameurl',
        ),
        migrations.RemoveField(
            model_name='url',
            name='name',
        ),
        migrations.RemoveField(
            model_name='url',
            name='posted_date',
        ),
    ]
