# Generated by Django 2.2.2 on 2019-07-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0003_auto_20190707_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notifyapp.Category'),
        ),
    ]
