# Generated by Django 2.2.2 on 2019-07-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0004_url_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='cat',
        ),
    ]
