# Generated by Django 2.2.2 on 2019-07-10 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0005_remove_url_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bookpublish', serialize=False, to='notifyapp.Url')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.AddField(
            model_name='url',
            name='Nb_notif',
            field=models.IntegerField(default=True),
        ),
    ]
