# Generated by Django 2.2.2 on 2019-07-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0006_auto_20190710_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='cat',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='notifyapp.Category'),
        ),
    ]
