# Generated by Django 2.2.2 on 2019-07-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0007_url_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifyapp.Category'),
        ),
    ]
