# Generated by Django 2.2.2 on 2019-07-11 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifyapp', '0008_auto_20190710_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='Nb_notif',
        ),
    ]
